//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCPDiscord.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SCPDiscord.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] english {
            get {
                object obj = ResourceManager.GetObject("english", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] english_emote {
            get {
                object obj = ResourceManager.GetObject("english_emote", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] finnish {
            get {
                object obj = ResourceManager.GetObject("finnish", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] finnish_emote {
            get {
                object obj = ResourceManager.GetObject("finnish_emote", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] french {
            get {
                object obj = ResourceManager.GetObject("french", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] french_emote {
            get {
                object obj = ResourceManager.GetObject("french_emote", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] italian {
            get {
                object obj = ResourceManager.GetObject("italian", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] italian_emote {
            get {
                object obj = ResourceManager.GetObject("italian_emote", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] polish {
            get {
                object obj = ResourceManager.GetObject("polish", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] polish_emote {
            get {
                object obj = ResourceManager.GetObject("polish_emote", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] russian {
            get {
                object obj = ResourceManager.GetObject("russian", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] russian_emote {
            get {
                object obj = ResourceManager.GetObject("russian_emote", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] overrides {
            get {
                object obj = ResourceManager.GetObject("overrides", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
